---
- name: Install Webserver
  hosts: all
  become: true
  tasks:
    - yum:
        name: httpd
        state: latest
    - service:
        name: httpd
        state: started
        enabled: true
